spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
    password: '${cipher}fe398753d9f055060821f17b2f0fc82d4fc0fe57c86772e97dbd250f7a3b2e3a'
    
userservice:
  registration:
   disabled: true
